# Generated by Django 4.1.5 on 2023-01-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_textblock_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textblock',
            old_name='path',
            new_name='image',
        ),
    ]
